name: Run tests

on:
  workflow_dispatch:
  workflow_call:

jobs:
  test:
    runs-on: ["self-hosted","java"]
    steps:
      - uses: actions/checkout@v3
      - run: |
          java --version
          mvn --version
      - run: mvn test --no-transfer-progress
      - name: Publish Test Report
        if: ${{ always() }}
        uses: scacap/action-surefire-report@v1