{{- if .Values.externalSecret.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "helm_chart.fullname" . }}
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRefName }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.externalSecret.target.secretName }}
  data:
    {{- toYaml .Values.externalSecret.data | nindent 4 }}
{{- end }}
