{{- if .Values.externalSecret.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "helm_chart.fullname" . }}
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRefName }}
    kind: ClusterSecretStore
  {{- range .Values.externalSecret.targets }}
  target:
    name: {{ .secretName }}
  data:
    {{- toYaml .data | nindent 4 }}
  {{- end }}
{{- end }}
