apiVersion: skaffold/v3
kind: Config
profiles:
  - name: dev
    deploy:
      helm:
        flags:
          upgrade:
            - --install
        releases:
          - name: skaffold-<example_application>
            chartPath: k8s/helm
  - name: staging
    deploy:
      helm:
        flags:
          upgrade:
            - --install
        releases:
          - name: skaffold-<example_application>
            chartPath: k8s/helm
            valuesFiles:
              - k8s/helm/values/staging.yaml
  - name: production
    deploy:
      helm:
        flags:
          upgrade:
            - --install
        releases:
          - name: skaffold-<example_application>
            chartPath: k8s/helm
            valuesFiles:
              - k8s/helm/values/production.yaml