name: Cypress UI Test

on:
  workflow_call:
    inputs:
      branch:
        type: string
        required: true
      type:
        type: string
        required: true
  workflow_dispatch:
    inputs:
      branch:
        type: string
        required: true
      type:
        type: string
        required: true

jobs:
  cypress-test:
    runs-on: ["self-hosted","node"]
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          npm ci
      - name: Start app
        run: |
          npm start &
      - name: Cypress test
        run: |
          if [[ ${{ inputs.type }} == 'push' ]]; then
            npm run runheadless -- --browser chrome
          elif [[ ${{ inputs.type }} == 'nightly' ]]; then
            npm run runnightly
          fi
