name: Cypress UI Test

on:
  workflow_call:

jobs:
  cypress-test:
    runs-on: ["self-hosted","node"]
    steps:
      - uses: actions/checkout@v3
      - name: Build and test
        run: |
          npm ci
          npm start
          npm run runheadless
        env:
          NODE_ENV: production
          SIERRA_CONFIG: https://cdn.rcsb.org/config/c5aecb46a9fe2698498ed4d1ab1925e9a8fef7f5/profiles/parks/sierra/sierra-base.app.json
