name: Cypress UI Test

on:
  workflow_call:

jobs:
  cypress-test:
    runs-on: ["self-hosted","node"]
    steps:
      - uses: actions/checkout@v3

      - name: Cypress install
        uses: cypress-io/github-action@v5.6.1

      - name: Build and test
        run: |
          npm ci
          npm run runheadless
