name: Skaffold Deploy
# Call the Skaffold command to deploy resources into the Kubernetes cluster.

on:
  workflow_call:
    inputs:
      namespace:
        type: string
        required: true
        description: "The namespace into which the resources will be deployed."
      profile:
        type: string
        required: true
        description: "The skaffold profile to use for the deployment."

jobs:
  skaffold-deploy:
    runs-on:
      - self-hosted
      - skaffold
    steps:
      - uses: actions/checkout@v4
      - name: Skaffold Deploy
        run: |
          skaffold deploy --namespace=${{ inputs.namespace }} --profile=${{ inputs.profile }}