# TODO remove once we are out of OpenStack and build-locker artifacts are not needed anymore
name: Deploy to Buildlocker

on:
  workflow_call:
    inputs:
      distribution:
        type: string
        required: true
      type:
        type: string
        required: true
      branch:
        type: string
        required: false
      node_version:
        type: string
        default: "16"

jobs:
  deploy-build-locker-jar:
    if: ${{ inputs.type =='jar' }}
    runs-on:
      - self-hosted
      - java
    steps:
      # NOTE: by default checkout will get the revision at workflow trigger time. Here we want the latest (including commits from previous jobs), that's why we need the fetch-depth and pull
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Pull latest changes
        run: |
          git pull origin ${{ github.ref_name }}
      - name: Build
        run: |
          mvn clean install --no-transfer-progress -Dmaven.test.skip=true
      - name: Deploy to Buildlocker
        run: |
          cd target
          tar -czvf ${{ inputs.distribution }}.tgz *.jar
          test -e ${{ inputs.distribution }}.tgz
          sshpass -p $(cat ~/.secrets/buildlocker_transporter_pw.txt) sftp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null transporter@bl-receive.rcsb.org:1-receive <<< $"put ${{ inputs.distribution }}.tgz"
  deploy-build-locker-war:
    if: ${{ inputs.type =='war' }}
    runs-on:
      - self-hosted
      - java
    steps:
      # NOTE: by default checkout will get the revision at workflow trigger time. Here we want the latest (including commits from previous jobs), that's why we need the fetch-depth and pull
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Pull latest changes
        run: |
          git pull origin ${{ github.ref_name }}
      - name: Build
        run: |
          mvn clean install --no-transfer-progress -Dmaven.test.skip=true
      - name: Deploy to Buildlocker
        run: |
          cd target
          mv *.war ${{ inputs.distribution }}.war
          test -e ${{ inputs.distribution }}.war
          sshpass -p $(cat ~/.secrets/buildlocker_transporter_pw.txt) sftp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null transporter@bl-receive.rcsb.org:1-receive <<< $"put ${{ inputs.distribution }}.war"
  deploy-build-locker-node:
    if: ${{ inputs.type =='node' }}
    runs-on:
      - self-hosted
      - "node-${{ inputs.node_version }}"
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          npm ci
          npm run lint
          npm run build --if-present
      - name: Convert Branch to Lowercase
        id: convert_to_lower
        uses: Entepotenz/change-string-case-action-min-dependencies@v1
        with:
          string: ${{ inputs.branch }}
      - name: Deploy to Buildlocker
        run: |
          tar czf ${{ inputs.distribution }}-${{ steps.convert_to_lower.outputs.lowercase }}.tgz *
          test -e ${{ inputs.distribution }}-${{ steps.convert_to_lower.outputs.lowercase }}.tgz
          ls -lrt ${{ inputs.distribution }}-${{ steps.convert_to_lower.outputs.lowercase }}.tgz
          /usr/bin/sshpass -p $(cat ~/.secrets/buildlocker_transporter_pw.txt) sftp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null transporter@bl-receive.rcsb.org:1-receive <<< $"put ${{ inputs.distribution }}-${{ steps.convert_to_lower.outputs.lowercase }}.tgz"
