name: Deploy to Buildlocker

on:
  workflow_call:
    inputs:
      distribution:
        type: string
        required: true
      type:
        type: string
        required: true
      branch:
        type: string
        required: false

jobs:
  deploy-build-locker-jar:
    if: ${{ inputs.type =='jar' }}
    runs-on:
      - self-hosted
      - java
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          mvn clean install --no-transfer-progress -Dmaven.test.skip=true
      - name: Deploy to Buildlocker
        run: |
          cd target
          tar -czvf ${{ inputs.distribution }}.tgz *.jar
          test -e ${{ inputs.distribution }}.tgz
          sshpass -p $(cat ~/.secrets/buildlocker_transporter_pw.txt) sftp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null transporter@bl-receive.rcsb.org:1-receive <<< $"put ${{ inputs.distribution }}.tgz"
  deploy-build-locker-war:
    if: ${{ inputs.type =='war' }}
    runs-on:
      - self-hosted
      - java
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          mvn clean install --no-transfer-progress -Dmaven.test.skip=true
      - name: Deploy to Buildlocker
        run: |
          cd target
          mv *.war ${{ inputs.distribution }}.war
          test -e ${{ inputs.distribution }}.war
          sshpass -p $(cat ~/.secrets/buildlocker_transporter_pw.txt) sftp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null transporter@bl-receive.rcsb.org:1-receive <<< $"put ${{ inputs.distribution }}.war"
  deploy-build-locker-node:
    if: ${{ inputs.type =='node' }}
    runs-on:
      - self-hosted
      - node
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          npm ci
          npm run lint
          npm run build --if-present
      - name: Deploy to Buildlocker
        run: |
          tar -czf ${{ inputs.distribution }}-${{ inputs.branch }}.tgz *
          test -e ${{ inputs.distribution }}-${{ inputs.branch }}.tgz
          /usr/bin/sshpass -p $(cat /home/runner/.secrets/buildlocker_transporter_pw.txt) sftp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null transporter@bl-receive.rcsb.org:1-receive <<< $"put ${{ inputs.distribution }}-${{ inputs.branch }}.tgz"
