name: Deploy to Buildlocker

on:
  workflow_call:
    inputs:
      distribution:
        type: string
        required: true
      type:
        type: string
        required: true

jobs:
  deploy-build-locker-jar:
    if: inputs.type == "jar"
    runs-on:
      - self-hosted
      - java
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          mvn clean install --no-transfer-progress -Dmaven.test.skip=true
      - name: Deploy to Buildlocker
        run: |
          cd target
          tar -czvf ${{ inputs.distribution }}.tgz *.jar
          test -e ${{ inputs.distribution }}.tgz
          sshpass -p $(cat ~/.secrets/buildlocker_transporter_pw.txt) sftp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null transporter@bl-receive.rcsb.org:1-receive <<< $"put ${{ inputs.distribution }}.tgz"
  deploy-build-locker-war:
    if: inputs.type == "war"
    runs-on:
      - self-hosted
      - java
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          mvn clean install --no-transfer-progress -Dmaven.test.skip=true
      - name: Deploy to Buildlocker
        run: |
          cd target
          test -e ${{ inputs.distribution }}.war
          sshpass -p $(cat ~/.secrets/buildlocker_transporter_pw.txt) sftp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null transporter@bl-receive.rcsb.org:1-receive <<< $"put ${{ inputs.distribution }}.war"
