name: Build and push images

on:
  workflow_call:
    inputs:
      harbor_project:
        description: The project in Harbor that the image will be associated with
        type: string
        required: true
      harbor_repository_name:
        description: The repository name of the image in Harbor
        type: string
        required: true
  workflow_dispatch:
    inputs:
      harbor_project:
        description: The project in Harbor that the image will be associated with
        type: string
        required: true
      harbor_repository_name:
        description: The repository name of the image in Harbor
        type: string
        required: true

jobs:
  build-and-push-images:
    runs-on: ["self-hosted","dind"]
    steps:
      - uses: actions/checkout@v4
      # Login to RCSB Harbor registry is setup within the GitHub Actions runner environment
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Docker image metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: harbor.devops.k8s.rcsb.org/${{ inputs.harbor_project }}/${{ inputs.harbor_repository_name }}
          tags: |
            # set latest tag for default branch
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
      - name: Build and Push Images
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}"
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}