# A workflow to find the current version from pom and then commit the release version (with tag) and the next dev cycle version
# Note this uses java-java-update-version.yaml
name: Roll maven version
on:
  workflow_call:

jobs:
  extract:
    name: extract-version
    runs-on:
      - self-hosted
      - java
    outputs:
      major: ${{ steps.major.outputs.major }}
      minor: ${{ steps.minor.outputs.minor }}
      patch: ${{ steps.patch.outputs.patch }}
    steps:
      - uses: actions/checkout@v4
      - id: get-version
        run: |
          echo "major=$(mvn --quiet build-helper:parse-version help:evaluate -Dexpression=parsedVersion.majorVersion -DforceStdout --no-transfer-progress)" >> $GITHUB_OUTPUT 
          echo "minor=$(mvn --quiet build-helper:parse-version help:evaluate -Dexpression=parsedVersion.minorVersion -DforceStdout --no-transfer-progress)" >> $GITHUB_OUTPUT
          echo "patch=$(mvn --quiet build-helper:parse-version help:evaluate -Dexpression=parsedVersion.incrementalVersion -DforceStdout --no-transfer-progress)" >> $GITHUB_OUTPUT
      - id: echo-version
        run: |
          echo ${{steps.get-version.outputs.major}}.${{steps.get-version.outputs.minor}}.${{steps.get-version.outputs.patch}}
  update-version:
    needs: extract
    uses: ./.github/workflows/java-update-version.yaml
    with:
      major: ${{ needs.extract.outputs.major }}
      minor: ${{ needs.extract.outputs.minor }}
      patch: ${{ needs.extract.outputs.patch }}
