name: Publish package to the Internal Maven Repository
on:
  push:

jobs:
  publish:
    runs-on:
      - self-hosted
      - java
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Publish package
        run: mvn --batch-mode --errors -U clean deploy
