name: Build and Deploy Node

on:
  workflow_call:
    inputs:
      distribution:
        type: string
        required: true
      branch:
        type: string
        required: true
      do_skaffold_deploy:
        type: boolean
        default: true

jobs:
  build-and-push-node-to-buildlocker:
    uses: rcsb/devops-cicd-github-actions/.github/workflows/deploy-to-buildlocker.yaml@master
    with:
      distribution: ${{ inputs.distribution }}
      branch: ${{ inputs.branch }}
      type: node
  call-skaffold-deploy:
    uses: rcsb/devops-cicd-github-actions/.github/workflows/skaffold-deploy.yaml@k8s-staging
    if: ${{ inputs.do_skaffold_deploy }}
