name: Build and Deploy Node

on:
  workflow_call:
    inputs:
      distribution:
        type: string
        required: true
      branch:
        type: string
        required: true

jobs:
  build:

    runs-on:
      - self-hosted
      - ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Build
        run: |
          npm ci
          npm run build --if-present

      - name: Deploy to Buildlocker
        run: |
          sudo apt-get install -y sshpass
          tar -czf ${{ inputs.distribution }}-${{ inputs.branch }}.tgz *
          test -e ${{ inputs.distribution }}-${{ inputs.branch }}.tgz
          sshpass -p $(cat /runner/.secrets/buildlocker_transporter_pw.txt) sftp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null transporter@bl-receive.rcsb.org:1-receive <<< $"put ${{ inputs.distribution }}-${{ inputs.branch }}.tgz"
