name: Build and Deploy Node

on:
  workflow_call:
    inputs:
      distribution:
        type: string
        required: true
      branch:
        type: string
        required: true
      type:
        type: string
        required: false

jobs:
  build-and-push-node-to-buildlocker:
    uses: rcsb/devops-cicd-github-actions/.github/workflows/deploy-to-buildlocker.yaml@master
    with:
      distribution: ${{ inputs.distribution }}
      branch: ${{ inputs.branch }}
      type: node
