name: Build and Deploy Node

on:
  workflow_call:
    inputs:
      distribution:
        type: string
        required: true
      branch:
        type: string
        required: true
      type:
        type: string
        required: false
      node_version:
        type: string
        default: "16"

jobs:
  build-and-push-node-to-buildlocker:
    uses: ./.github/workflows/deploy-to-buildlocker.yaml
    with:
      distribution: ${{ inputs.distribution }}
      branch: ${{ inputs.branch }}
      type: node
      node_version: ${{ inputs.node_version }}
