name: Build and Deploy Node

on:
  workflow_call:
    inputs:
      distribution:
        type: string
        required: true
      branch:
        type: string
        required: true
      type:
        type: string
        required: false

jobs:
  cypress-test:
    if: ${{ inputs.distribution =='sierra' }}
    uses: rcsb/devops-cicd-github-actions/.github/workflows/cypress.yaml@dev-jh-node
    with:
      branch: ${{ inputs.branch }}
      type: ${{ inputs.type }}

  build-and-push-to-buildlocker:
    needs: cypress-test
    uses: rcsb/devops-cicd-github-actions/.github/workflows/deploy-to-buildlocker.yaml@dev-jh-node
    with:
      distribution: ${{ inputs.distribution }}
      branch: ${{ inputs.branch }}
      type: node

  build-and-push-docker-images:
    needs: cypress-test
    runs-on: ["self-hosted","test-node"]
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          npm  ci
          npm run build --if-present
       #LogintoRCSBHarborregistryissetupwithintheGitHubActionsrunnerenvironment
      - name: Docker image metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: harbor.devops.k8s.rcsb.org/rcsb/rcsb-${{ inputs.distribution }}
          tags: |
            #setlatesttagfordefaultbranch
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
      - name: Build and PushImages - ${{ inputs.distribution }}
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name!='pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
