name: Build and Deploy Node

on:
  workflow_call:
    inputs:
      distribution:
        type: string
        required: true
      branch:
        type: string
        required: true

jobs:
#  cypress-test:
#    uses: rcsb/devops-cicd-github-actions/.github/workflows/cypress.yaml@dev-jh-node

  build-and-push-to-buildlocker:
    uses: rcsb/devops-cicd-github-actions/.github/workflows/deploy-to-buildlocker.yaml@dev-jh-node
    with:
      distribution: ${{ inputs.distribution }}
      branch: ${{ inputs.branch }}
      type: node

#  build-and-push-docker-images:
#    runs-on: ["self-hosted","node"]
#    steps:
#      - uses: actions/checkout@v3
#      - name: Build
#        run: |
#          npm ci
#          npm run build --if-present
#      - name: Login to Nexus3
#        env:
#          pw: $(cat ~/.secrets/nexus3_pw.txt)
#        uses: docker/login-action@v2
#        with:
#          registry: nexus3.rcsb.org
#          username: gha-runner-docker
#          password: $pw
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v2
#      - name: Docker image metadata
#        id: meta
#        uses: docker/metadata-action@v4
#        with:
#          images: nexus3.rcsb.org/rcsb/${{ inputs.distribution }}
#          tags: |
#            # set latest tag for default branch
#            type=raw,value=latest,enable={{is_default_branch}}
#            type=ref,event=branch
#            type=ref,event=tag
#            type=ref,event=pr
#      - name: Build and Push Images - ${{ inputs.distribution }}
#        uses: docker/build-push-action@v3
#        with:
#          context: "{{defaultContext}}:${{ inputs.distribution }}"
#          push: ${{ github.event_name != 'pull_request' }}
#          tags: ${{ steps.meta.outputs.tags }}
#          labels: ${{ steps.meta.outputs.labels }}
