name: Build and Deploy Node

on:
  workflow_call:

jobs:
  build:

    runs-on:
      - self-hosted
      - ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - name: Use Node 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
