name: Build and Deploy Node

on:
  workflow_call:
    inputs:
      distribution:
        type: string
        required: true
      branch:
        type: string
        required: true
      do_skaffold_deploy:
        type: boolean
        default: true

jobs:
  call-skaffold-deploy:
    uses: rcsb/devops-cicd-github-actions/.github/workflows/deploy_skaffold.yaml@k8s-staging
    if: ${{ inputs.do_skaffold_deploy }}
    with:
      namespace: staging
      profile: staging
