name: Push to Branch

on:
  workflow_call:
    inputs:
      distribution:
        type: string
        required: true
      type:
        type: string
        default: "jar"
        required: false
      do_skaffold_deploy:
        type: boolean
        default: false
      namespace:
        type: string
        required: false
      profile:
        type: string
        required: false

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: rcsb/devops-cicd-github-actions/.github/workflows/run-tests.yaml@master
  call-build-and-push-docker:
    needs: test
    uses: rcsb/devops-cicd-github-actions/.github/workflows/jib-build-and-push-docker.yaml@k8s-staging
    with:
      tag: "${{ github.ref_name }}"
  call-deploy-to-buildlocker:
    needs: test
    uses: rcsb/devops-cicd-github-actions/.github/workflows/deploy-to-buildlocker.yaml@master
    with:
      distribution: ${{ inputs.distribution }}
      type: ${{ inputs.type }}
  call-skaffold-deploy:
    if: ${{ inputs.do_skaffold_deploy }}
    needs: call-build-and-push-docker
    uses: rcsb/devops-cicd-github-actions/.github/workflows/skaffold-deploy.yaml@k8s-staging
    with:
      namespace: ${{ inputs.namespace }}
      profile: ${{ inputs.profile }}
