name: Push to Master Branch
on:
  push:
    branches:
      - "master"
      - "main"
  workflow_call:
    inputs:
      distribution:
        type: string
        required: true
      type:
        type: string
        default: "jar"
        required: false

jobs:
  test:
    if: |
      !contains(github.event.head_commit.message, '[actions]')
    uses: rcsb/devops-cicd-github-actions/.github/workflows/run-tests.yaml@master
  extract:
    name: extract-version
    needs: test
    runs-on:
      - self-hosted
      - java
    outputs:
      major: ${{ steps.major.outputs.major }}
      minor: ${{ steps.minor.outputs.minor }}
      patch: ${{ steps.patch.outputs.patch }}
    steps:
      - uses: actions/checkout@v3
      - id: major
        run: |
          echo ::set-output name=major::$(mvn build-helper:parse-version help:evaluate -Dexpression=parsedVersion.majorVersion -q -DforceStdout --no-transfer-progress)
      - id: minor
        run: |
          echo ::set-output name=minor::$(mvn build-helper:parse-version help:evaluate -Dexpression=parsedVersion.minorVersion -q -DforceStdout --no-transfer-progress)
      - id: patch
        run: |
          echo ::set-output name=patch::$(mvn build-helper:parse-version help:evaluate -Dexpression=parsedVersion.incrementalVersion -q -DforceStdout --no-transfer-progress)
  echo-version:
    runs-on: ubuntu-latest
    needs: extract
    steps:
      - run: echo ${{needs.extract.outputs.major}}.${{needs.extract.outputs.minor}}.${{needs.extract.outputs.patch}}
  call-release:
    needs: extract
    uses: rcsb/devops-cicd-github-actions/.github/workflows/release.yaml@master
    with:
      major: "${{needs.extract.outputs.major}}"
      minor: "${{needs.extract.outputs.minor}}"
      patch: "${{needs.extract.outputs.patch}}"
      skip-tests : true
      distribution: "${{ inputs.distribution }}"
      type: "${{ inputs.type }}"
