# TODO deprecate: make sure no other repos use this anymore and remove
name: Release

on:
  workflow_call:
    inputs:
      major:
        description: 'Major version'
        type: string
        required: true
      minor:
        description: 'Minor version'
        type: string
        required: true
      patch:
        description: 'Patch version'
        type: string
        required: true
      skip-tests:
        description: 'Skip tests'
        type: boolean
        default: true
        required: false
      distribution:
        description: 'buildlocker distribution name'
        type: string
        required: true
      type:
        description: 'buildlocker distribution type [war|jar*]'
        type: string
        required: false

jobs:
  run-tests:
    if: inputs.skip-tests != true
    uses: ./.github/workflows/run-tests.yaml
  call-update-version:
    uses: ./.github/workflows/java-update-version.yaml
    with:
      major: "${{ inputs.major }}"
      minor: "${{ inputs.minor }}"
      patch: "${{ inputs.patch }}"
  call-build-and-push-docker:
    uses: ./.github/workflows/build-and-push-docker.yaml
    with:
      tag: "${{ inputs.major }}.${{ inputs.minor }}.${{ inputs.patch }}"
  call-deploy-to-build-locker:
    needs:
      - call-build-and-push-docker
    uses: ./.github/workflows/deploy-to-buildlocker.yaml
    with:
      distribution: "${{ inputs.distribution }}"
      type: "${{ inputs.type }}"