name: Run After Commit
on:
  workflow_run:
    workflows: [ "Commit to Branch" ]
    types:
      - completed
  workflow_dispatch:

jobs:
  after-commit:
    runs-on:
      - self-hosted
      - java
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check file
        run: |
          cat testfile.txt
