name: Skaffold Deploy

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to be used as a docker image tag i.e. project version"
        type: string
        required: false
        default: latest
      namespace:
        description: "K8s namespace to which perform the deployment"
        type: string
        required: true
  workflow_call:
    inputs:
      tag:
        type: string
        required: false
        default: latest
      namespace:
        type: string
        required: false
        default: ""

jobs:
  skaffold-deploy:
    runs-on:
      - self-hosted
      - skaffold
    steps:
      - uses: actions/checkout@v3
      - name: Determine namespace for release
        run: |
          if [ ${{ inputs.namespace }} != "" ]; then
            echo "NAMESPACE=${{ inputs.namespace }} >> $GITHUB_ENV
          elif [ ${{ github.ref_name }} == "production" ]; then
            echo "NAMESPACE=production" >> $GITHUB_ENV
          elif [ ${{ github.ref_name }} == "staging" ]; then
            echo "NAMESPACE=staging" >> $GITHUB_ENV
          else
            echo "::error title="Unknown release namespace"::"The release namespace could not be determined. Either no namespace value was passed in as an input to the workflow call, or the branch name does not match one of the default expected names."
            exit 1
          fi
          echo "Deploying into the $NAMESPACE namespace"
      - name: Skaffold Deploy from Dispatch
        run: |
          skaffold deploy --namespace=${{ env.NAMESPACE }} --tag=${{ inputs.tag }}