name: Skaffold Deploy

on:
  workflow_call:
    inputs:
      namespace:
        type: string
        required: true
      profile:
        type: string
        required: true

jobs:
  skaffold-deploy:
    runs-on:
      - self-hosted
      - skaffold
    steps:
      - uses: actions/checkout@v3
      - name: Skaffold Deploy
        run: |
          skaffold deploy --namespace=${{ inputs.namespace }} --profile=${{ inputs.profile }}