name: Skaffold Deploy

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to be used as a docker image tag i.e. project version"
        type: string
        required: false
        default: latest
      namespace:
        description: "K8s namespace to which perform the deployment"
        type: string
        required: true
  workflow_call:
    inputs:
      tag:
        type: string
        required: false
        default: latest
      namespace:
        type: string
        required: false
        default: |
          if [ ${{ input.branch }} = "production" ]; then
            production
          elif [ ${{ input.branch }} = "staging" ]; then
            staging
          elif
            echo "::error title="Unknown release namespace"::"The release namespace could not be determined. Either no namespace value was passed in as an input to the workflow call, or the branch name does not match one of the default expected names."
          fi

jobs:
  skaffold-deploy:
    runs-on:
      - self-hosted
      - skaffold
    steps:
      - uses: actions/checkout@v3
      - name: Skaffold Deploy from Dispatch
        run: |
          skaffold deploy --namespace=${{ inputs.namespace }} --tag=${{ inputs.tag }}