name: Skaffold Deploy

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to be used as a docker image tag i.e. project version"
        type: string
        required: false
        default: latest
      namespace:
        description: "K8s namespace to which perform the deployment"
        type: string
        required: true
      do_skaffold_deploy:
        description: "Allow workflow to perform skaffold deployment"
        type: boolean
        default: true
  workflow_call:
    inputs:
      tag:
        type: string
        required: false
      namespace:
        type: string
        required: false
        default: ""
      do_skaffold_deploy:
        type: boolean
        default: true

jobs:
  skaffold-deploy:
    runs-on:
      - self-hosted
      - skaffold
    if: ${{ inputs.do_skaffold_deploy }}
    steps:
      - uses: actions/checkout@v3
      - name: Determine environment for release
        run: |
          if [ ! -z "${{ inputs.namespace }}" ]; then
            echo "NAMESPACE=${{ inputs.namespace }}" >> $GITHUB_ENV
            echo "SKAFFOLD_PROFILE=dev" >> $GITHUB_ENV
          elif [ "${{ github.ref_name }}" == "production" ]; then
            echo "NAMESPACE=production" >> $GITHUB_ENV
            echo "SKAFFOLD_PROFILE=production" >> $GITHUB_ENV
          elif [ "${{ github.ref_name }}" == "staging" ] || \
               [ "${{ github.ref_name }}" == "k8s-staging" ] ; then
            echo "NAMESPACE=staging" >> $GITHUB_ENV
            echo "SKAFFOLD_PROFILE=staging" >> $GITHUB_ENV
          else
            echo "::error title=Unknown release namespace::The release namespace could not be determined. Either no namespace value was passed in as an input to the workflow call, or the branch name does not match one of the default expected names."
            exit 1
          fi
          echo "Deploying into the $(echo $GITHUB_ENV | grep NAMESPACE) namespace."
          echo "Using the $(echo $GITHUB_ENV | grep SKAFFOLD_PROFILE) profile for the skaffold deployment."
      - name: Skaffold Deploy from Dispatch
        run: |
          skaffold deploy --namespace=${{ env.NAMESPACE }} --profile=${{ env.SKAFFOLD_PROFILE }} $( if [ ! -z "${{ inputs.tag }}" ]; then echo "--tag=${{ inputs.tag }}"; fi )