name: Update Version

on:
  workflow_dispatch:
    inputs:
      major:
        description: 'Major version'
        required: true
      minor:
        description: 'Minor version'
        required: true
      patch:
        description: 'Patch version'
        required: true

  workflow_call: {}

env:
  NEW_VERSION: "${{ github.event.inputs.major }}.${{ github.event.inputs.minor }}.${{ github.event.inputs.patch }}"

jobs:
  update-version:
    runs-on:
      - self-hosted
      - java
    steps:
      - uses: actions/checkout@v3
      - name: Setup git author information
        run: |
          git config user.name RCSBSystem
          git config user.email it@rcsb.org
      - run: mvn --version
      - name: Set version
        run: mvn versions:set -DnewVersion=$NEW_VERSION --no-transfer-progress
      - name: Commit and tag new version
        run: |
          git add pom.xml
          git commit -m "[actions] Updated version in pom.xml to $NEW_VERSION"
          git tag $VERSION
      - name: Increment version
        run: |
          NEXT_PATCH=$(mvn build-helper:parse-version help:evaluate -Dexpression=parsedVersion.nextIncrementalVersion -q -DforceStdout --no-transfer-progress)
          mvn versions:set -DnewVersion="${{ github.event.inputs.major }}.${{ github.event.inputs.minor }}.$NEXT_PATCH-SNAPSHOT" -DallowSnapshots --no-transfer-progress
      - name: Commit and tag new version
        run: |
          git add pom.xml
          git commit -m "[actions] Next development cycle"
      - name: Push back to GitHub
        run: git push --all
