name: Node Workflow
# Standard workflow for any NodeJS based projects.

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build_npm:
    name: "Build via NPM"
    uses: ./.github/workflows/run_npm.yaml
    with:
      script: "build"
  lint_npm:
    name: "Lint via NPM"
    uses: ./.github/workflows/run_npm.yaml
    with:
      script: "lint"
  lint_docker:
    name: "Lint Dockerfile"
    uses: ./.github/workflows/lint_docker.yaml
  test_npm:
    name: "Run unit tests via NPM"
    needs:
      - build_npm
      - lint_npm
      - lint_docker
    uses: ./.github/workflows/run_npm.yaml
    with:
      script: "test"
  build_docker:
    name: "Build docker image"
    needs:
      - build_npm
      - lint_npm
      - lint_docker
    uses: ./.github/workflows/build_docker.yaml
    with:
      repo_project: "rcsb"
      docker_image_name: "rcsb-sierra"
  skaffold_deploy_staging:
    name: "Skaffold deploy into staging namespace"
    if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
    needs:
      - test_npm
      - build_docker
    uses: ./.github/workflows/deploy_skaffold.yaml
    with:
      namespace: staging
      profile: staging
  skaffold_deploy_production:
    name: Skaffold deploy into production environment"
    if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
    needs:
      - skaffold_deploy_staging
    uses: ./.github/workflows/deploy_skaffold.yaml
    with:
      namespace: production
      profile: production

