name: Node Workflow
# Standard workflow for any NodeJS based projects.

on:
  workflow_call:
    inputs:
      mainline_branch:
        type: string
        default: format('refs/heads/{0}', github.event.repository.default_branch)
        description: "The mainline branch for the repo. Deployments to the staging and production environments are done only on push to this branch. Defaults to the repo's default branch."
  workflow_dispatch:
    inputs:
      mainline_branch:
        type: string
        default: format('refs/heads/{0}', github.event.repository.default_branch)
        description: "The mainline branch for the repo. Deployments to the staging and production environments are done only on push to this branch. Defaults to the repo's default branch."

jobs:
  # Build jobs
  build_npm:
    name: "Build via NPM"
    uses: ./.github/workflows/run_npm.yaml
    with:
      script: "build"
  lint_npm:
    name: "Lint via NPM"
    uses: ./.github/workflows/run_npm.yaml
    with:
      script: "lint"
  lint_docker:
    name: "Lint Dockerfile"
    uses: ./.github/workflows/lint_docker.yaml
  # Test jobs
  test_npm:
    name: "Run unit tests via NPM"
    needs:
      - build_npm
      - lint_npm
      - lint_docker
    uses: ./.github/workflows/run_npm.yaml
    with:
      script: "test"
  build_docker:
    name: "Build docker image"
    needs:
      - build_npm
      - lint_npm
      - lint_docker
    uses: ./.github/workflows/build_docker.yaml
    with:
      repo_url: "${{ inputs.repo_url }}"
      repo_project: "${{ inputs.repo_project }}"
      docker_image_name: "${{ inputs.docker_image_name }}"
  # Staging jobs
  build_docker_staging:
    name: "Push docker image with staging tag"
    if: (github.ref == "refs/heads/${{ inputs.mainline_branch }}") && (github.event_name != 'pull_request')
    needs:
      - test_npm
      - build_docker
    uses: ./.github/workflows/retag_docker.yaml
    with:
      repo_url: "${{ inputs.repo_url }}"
      repo_project: "${{ inputs.repo_project }}"
      docker_image_name: "${{ inputs.docker_image_name }}"
      old_tag: "${{ github.ref_name }}"
      new_tag: "staging"
  skaffold_deploy_staging:
    name: "Skaffold deploy into staging namespace"
    if: (github.ref == "refs/heads/${{ inputs.mainline_branch }}") && (github.event_name != 'pull_request')
    needs:
      - build_docker_staging
    uses: ./.github/workflows/deploy_skaffold.yaml
    with:
      namespace: staging
      profile: staging
  # Production jobs
  build_docker_production:
    name: "Push docker image with production tag"
    if: (github.ref == "refs/heads/${{ inputs.mainline_branch }}") && (github.event_name != 'pull_request')
    needs:
      - skaffold_deploy_staging
    uses: ./.github/workflows/retag_docker.yaml
    with:
      repo_url: "${{ inputs.repo_url }}"
      repo_project: "${{ inputs.repo_project }}"
      docker_image_name: "${{ inputs.docker_image_name }}"
      old_tag: "${{ github.ref_name }}"
      new_tag: "production"
  skaffold_deploy_production:
    name: Skaffold deploy into production environment"
    if: (github.ref == "refs/heads/${{ inputs.mainline_branch }}") && (github.event_name != 'pull_request')
    needs:
      - build_docker_production
    uses: ./.github/workflows/deploy_skaffold.yaml
    with:
      namespace: production
      profile: production

