# SPDX-FileCopyrightText: Copyright 2024, the RCSB PDB, University of California, Rutgers University, and contributors
# SPDX-FileCopyrightText: Copyright 2020-2024, Contributors to CICD
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/cicd
# SPDX-License-Identifier: Apache-2.0

# This workflow runs tests for pull requests and issue comments.
# It is triggered by pull request events (ready for review, synchronize, edited)
# and issue comments (created).
# The tests are conditional based on the state of the pull request (not in draft)
# and specific events.

name: Test PR
run-name: ${{ github.workflow }} ${{ github.ref_name }}

on:
  pull_request:
    types:
      - ready_for_review
      - synchronize
      - edited
  issue_comment:
    types:
      - created

jobs:
  test:
    name: Run tests for PR and issue comments
    # Run tests if the PR is ready for review, synchronized (and not in draft), or edited (and not in draft),
    # or if an issue comment is created.
    if: >
      github.event_name == 'pull_request' &&
        github.event.action == 'ready_for_review' ||
      github.event_name == 'pull_request' &&
        github.event.action == 'synchronize' &&
        github.event.pull_request.draft == false ||
      github.event_name == 'pull_request' &&
        github.event.action == 'edited' &&
        github.event.pull_request.draft == false ||
      github.event_name == 'issue_comment' &&
        github.event.action == 'created'
    uses: ./.github/workflows/_py-test.yaml
    secrets: inherit
